apiVersion: batch/v1
kind: Job
metadata:
  name: multi-test-job
spec:
  completions: 5
  template:
    metadata:
      labels:
        app: test-job
    spec:
      restartPolicy: OnFailure
      containers:
      - image: reg.cloud.com/batch-job
        name: main
