apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: nodejs
    spec:
      containers:
      - image: reg.cloud.com/node-express-info
        name: nodejs
